spring:
  application:
    name: LibraryReservationReviewHub
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_reservation_review_hub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

