  server:
    port: 8123
    servlet:
      context-path: /api

  spring:
    application:
      name: LibraryReservationReviewHub
    profiles:
      active: local

  # springdoc-openapi项目配置
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: 'default'
        paths-to-match: '/**'
        packages-to-scan: com.haochen.personaagenthub.controller
  # knife4j的增强配置，不需要增强可以不配
  knife4j:
    enable: true
    setting:
      language: zh_cn

  mybatis-plus:
    configuration:
      # MyBatis configuration
      map-underscore-to-camel-case: false
      # print log info
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-delete-field: isDelete
        logic-delete-value: 1
        logic-not-delete-value: 0

